(coq.theory
 (name Cyclic)
 (theories stdpp Stdlib Autosubst)
  (flags (:standard -w -notation-overridden))
   (modules
    Syntax.StrictPos
    Syntax.Term
    Syntax.Examples
    Syntax.ListNat
    Judgement.Typing
    Judgement.SequentTyping
    Semantics.Cbn
 
    Graph.FiniteDigraph
    Preproof.Preproof
    CyclicProof.CyclicProof
    CyclicProof.Ranked
  
    Progress.Ranking
    Progress.Measures
    Progress.Embedding
    Progress.PatternUnification
    Transform.ReadOffSpec
    Transform.ReadOff
    Transform.CyclicVertexSpec
    Transform.ReadOffPreproof
    Transform.ReadOffSequentPreproof
    Transform.ReadOffDrivingPreproof
    Transform.ProofGraphRewrite
    Transform.CyclicTraceCondition
    Transform.Extract
    Transform.CyclicRules
    Transform.CyclicSequentRules
    Transform.BetaReduce
    Transform.Supercompile
    Transform.SupercompilationCorrespondence
    Transform.SupercompileTrace
     Transform.CaseCase
     Transform.SequentDrivingRules
     Transform.SequentObservationRules
      Transform.CaseCaseProof

     Transform.ScrutineeProp
     Transform.ReadOffExtractCorrectness
    Equiv.Bisimulation
    Equiv.CIU
    Equiv.CIUJudgement
    Equiv.CIUNatObs
    Equiv.CIUChecklistLengthMap
    Equiv.SupercompileChecklistIndexPipeline))


