(coq.theory
 (name Cyclic)
 (theories stdpp Stdlib Autosubst)
  (flags (:standard -w -notation-overridden))
   (modules
    Syntax.StrictPos
    Syntax.Term
    Syntax.Examples
    Syntax.ListNat
    Judgement.Typing
    Judgement.SequentTyping
    Semantics.Cbn
 
    Graph.FiniteDigraph
    Preproof.Preproof
    CyclicProof.CyclicProof
    CyclicProof.Ranked
  
    Progress.Ranking
    Progress.Measures
    Progress.Embedding
    Progress.PatternUnification
    Transform.ReadOffSpec
    Transform.ReadOff
    Transform.CyclicVertexSpec
    Transform.ReadOffPreproof
    Transform.ReadOffSequentPreproof
    Transform.ReadOffDrivingPreproofDefs
    Transform.ReadOffDrivingPreproof
     Transform.ProofGraphRewrite
      Transform.CyclicTraceCondition
      Transform.CyclicTraceConditionObsTree
      Transform.CyclicTraceConditionBudget
      Transform.Extract
    Transform.CyclicRules
    Transform.CyclicSequentRules
    Transform.BetaReduce
     Transform.Supercompile
     Transform.SupercompileTest
     Transform.SupercompilationCorrespondence
     Transform.SupercompileTrace
     Transform.SupercompileTraceCheckSound
      Transform.SpeculationGen
      Transform.CanonRoundtrip
      Transform.LLMOracle
      Transform.SpeculationConjectures
      Transform.LemmaEnv
      Transform.LemmaProposer
      Transform.SortExamples
      Transform.OmegaRule
      Transform.OmegaExamples
      Transform.LLMLemmaInAction
      Transform.CompilerCorrectness
      Transform.GradualCast
      Transform.GradualCastExamples
      Transform.GradualCastVars
      Transform.SpeculationFires
      Transform.DependentVec
Transform.ConditionalLemmas
      Transform.Commutativity
      Transform.OmegaEq
      Transform.OmegaEqTest
      Transform.DependentPruning
      Transform.TypeIndexTrace
      Transform.MonadLaws
      Transform.IndexCalc
      Transform.LLMDemo
      Transform.HardTest
      Transform.HardTestRun
      Transform.LLMTest
      Transform.HardExamples
      Transform.CaseCase
     Transform.SequentDrivingRules
     Transform.SequentObservationRules
      Transform.CaseCaseProof

     Transform.ScrutineeProp
     Transform.ReadOffExtractCorrectness
    Equiv.Bisimulation
    Equiv.CIU
    Equiv.CIUJudgement
    Equiv.CIUNatObs
    Equiv.CIUChecklistLengthMap
    Equiv.SupercompileChecklistIndexPipeline))


